"""ITSM evidence masters for Jira Cloud (EV-* codes) and collection metadata."""

from __future__ import annotations

# Names from evidence_master catalog (ITSM / Jira). Category ITSM for all.
JIRA_ITSM_SEED_ROWS: list[dict[str, str]] = [
    {"code": "EV-35", "name": "Access Request Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-18", "name": "Asset Provisioning Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-19", "name": "Asset Decommissioning Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-27", "name": "Access Revocation Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-31", "name": "Security Incident Register — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-32", "name": "Incident Management Ticket Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-36", "name": "Access Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-38", "name": "Corrective Action Tracking Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-51", "name": "Security Alert Investigation Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-58", "name": "Static Code Analysis Vulnerability Tracking Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-62", "name": "Vendor Onboarding Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-71", "name": "Change Management Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-72", "name": "Change Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-99", "name": "Vulnerability Remediation Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-102", "name": "Change Management / Deployment Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-106", "name": "Change Request Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-145", "name": "Access Request and Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-147", "name": "Access Revocation Ticket Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-153", "name": "Data Subject Request Ticket Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-159", "name": "Production Data Access Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-229", "name": "Incident Management Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-213", "name": "Customer Support Ticket Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-220", "name": "Corrective Action Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-221", "name": "Corrective Action Tracking Reports — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-270", "name": "Data Subject Appeal Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-277", "name": "DSAR Request Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-278", "name": "DSAR Fulfillment Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-324", "name": "Emergency Change Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-325", "name": "Emergency Change Review Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-329", "name": "Customer Complaint Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-330", "name": "Complaint Resolution Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-338", "name": "Customer Feedback / Complaint Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-414", "name": "Incident Notification Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-347", "name": "Internal Support Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-351", "name": "AI Incident Management Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-373", "name": "User Behavior Investigation Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-381", "name": "Personal Data Correction Requests — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-387", "name": "Public Content Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-394", "name": "Insider Threat Investigation Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-408", "name": "Customer Engagement Activity Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-437", "name": "Customer Feedback Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-444", "name": "AI Concern Reporting Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-473", "name": "Security Incident Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-489", "name": "Data Disposal Request Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-507", "name": "Disaster Recovery Test Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-519", "name": "Access Review Approval Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-543", "name": "Data Subject Access Request Register — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-544", "name": "Data Subject Access Request Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-554", "name": "License Compliance Review Records — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-568", "name": "Vulnerability Report Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-13", "name": "AI Model Training Data Approval Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
    {"code": "EV-5", "name": "Backup Failure Incident Tickets — ITSM", "category": "ITSM", "api": "/rest/api/3/search"},
]

ALL_JIRA_ITSM_EVIDENCE_CODES: tuple[str, ...] = tuple(r["code"] for r in JIRA_ITSM_SEED_ROWS)
EVIDENCE_MASTER_NAME_ORDER: tuple[str, ...] = tuple(r["name"] for r in JIRA_ITSM_SEED_ROWS)
