"""Mock Darwinbox HRMS API layer."""

from __future__ import annotations

from datetime import date, datetime, timezone
from typing import Any


def _iso_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def get_employees(configuration_data: dict[str, Any]) -> list[dict[str, Any]]:
    company = configuration_data.get("company_name", "Acme Corp")
    now = _iso_now()
    return [
        {
            "employee_id": "EMP-1001",
            "employee_name": "Avery Chen",
            "employment_type": "full_time",
            "employment_status": "active",
            "department": "Information Security",
            "job_title": "Security Engineer II",
            "role": "Security Engineer",
            "hire_date": "2024-01-15",
            "manager_id": "EMP-1000",
            "manager_name": "Jordan Patel",
            "reporting_manager_id": "EMP-1000",
            "reporting_manager_name": "Jordan Patel",
            "disciplinary": {
                "record_id": "DISC-1001",
                "violation_type": "policy_breach",
                "policy_violated": "Access Control Policy",
                "incident_date": "2025-09-04",
                "investigation_conducted": True,
                "investigation_details": "Endpoint log review completed by internal audit.",
                "disciplinary_action_taken": "written_warning",
                "action_severity": "medium",
                "approved_by": "CISO",
                "action_date": "2025-09-10",
                "status": "closed",
            },
            "performance_review": {
                "record_id": "PR-1001",
                "review_cycle": "2025-H2",
                "self_review_completed": True,
                "manager_review_completed": True,
                "review_date": "2025-12-20",
                "performance_rating": "exceeds_expectations",
                "feedback_provided": True,
                "review_status": "completed",
            },
            "probation_review": {
                "record_id": "PB-1001",
                "probation_review_required": True,
                "probation_review_completed": True,
                "review_date": "2024-04-15",
                "evaluation_result": "confirmed",
                "review_status": "completed",
            },
            "candidate_interview": {
                "record_id": "INT-1001",
                "candidate_id": "CAN-1001",
                "candidate_name": "Avery Chen",
                "position_applied": "Security Engineer II",
                "interview_stage": "panel",
                "interviewer_id": "EMP-1000",
                "interviewer_name": "Jordan Patel",
                "evaluation_score": 4.6,
                "feedback": "Strong incident response knowledge.",
                "decision": "hire",
                "decision_date": "2023-12-12",
                "hiring_status": "joined",
            },
            "disclosure_check": {
                "record_id": "DISCLOSE-1001",
                "references": "Priya Nair",
                "contact_number": "+1-202-555-0101",
                "relation": "Former manager",
                "disclosed_to": "HR Compliance Team",
            },
            "company_name": company,
            "created_time": now,
            "last_updated_time": now,
        },
        {
            "employee_id": "EMP-1002",
            "employee_name": "Mina Flores",
            "employment_type": "full_time",
            "employment_status": "active",
            "department": "Engineering",
            "job_title": "ML Platform Engineer",
            "role": "AI Developer",
            "hire_date": "2023-08-01",
            "manager_id": "EMP-1010",
            "manager_name": "Noah Singh",
            "reporting_manager_id": "EMP-1010",
            "reporting_manager_name": "Noah Singh",
            "disciplinary": {
                "record_id": "DISC-1002",
                "violation_type": "none",
                "policy_violated": "",
                "incident_date": "2025-01-01",
                "investigation_conducted": False,
                "investigation_details": "",
                "disciplinary_action_taken": "none",
                "action_severity": "low",
                "approved_by": "HRBP",
                "action_date": "2025-01-02",
                "status": "not_applicable",
            },
            "performance_review": {
                "record_id": "PR-1002",
                "review_cycle": "2025-H2",
                "self_review_completed": True,
                "manager_review_completed": True,
                "review_date": "2025-12-18",
                "performance_rating": "meets_expectations",
                "feedback_provided": True,
                "review_status": "completed",
            },
            "probation_review": {
                "record_id": "PB-1002",
                "probation_review_required": True,
                "probation_review_completed": True,
                "review_date": "2023-11-01",
                "evaluation_result": "confirmed",
                "review_status": "completed",
            },
            "candidate_interview": {
                "record_id": "INT-1002",
                "candidate_id": "CAN-1002",
                "candidate_name": "Mina Flores",
                "position_applied": "ML Platform Engineer",
                "interview_stage": "final",
                "interviewer_id": "EMP-1010",
                "interviewer_name": "Noah Singh",
                "evaluation_score": 4.8,
                "feedback": "Strong model operations background.",
                "decision": "hire",
                "decision_date": "2023-07-10",
                "hiring_status": "joined",
            },
            "disclosure_check": {
                "record_id": "DISCLOSE-1002",
                "references": "Luis Ortega",
                "contact_number": "+1-202-555-0133",
                "relation": "Mentor",
                "disclosed_to": "Talent Acquisition",
            },
            "company_name": company,
            "created_time": now,
            "last_updated_time": now,
        },
    ]


def get_terminations(configuration_data: dict[str, Any]) -> list[dict[str, Any]]:
    now = _iso_now()
    return [
        {
            "record_id": "TERM-2001",
            "employee_id": "EMP-0991",
            "employee_name": "Lena Brooks",
            "employment_type": "full_time",
            "department": "Finance",
            "termination_date": "2025-11-30",
            "termination_reason": "voluntary_resignation",
            "termination_status": "completed",
            "last_working_day": "2025-11-28",
            "record_status": "closed",
            "checklist_id": "OFF-2001",
            "asset_return_completed": True,
            "access_revocation_completed": True,
            "knowledge_transfer_completed": True,
            "user_accounts_disabled": True,
            "checklist_status": "completed",
            "completed_by": "IT Operations",
            "completed_date": "2025-11-29",
            "created_time": now,
            "last_updated_time": now,
        }
    ]


def get_trainings(configuration_data: dict[str, Any]) -> list[dict[str, Any]]:
    now = _iso_now()
    return [
        {
            "record_id": "TRN-3001",
            "employee_id": "EMP-1001",
            "employee_name": "Avery Chen",
            "department": "Information Security",
            "role": "Security Engineer",
            "hire_date": "2024-01-15",
            "training_id": "SEC-101",
            "training_name": "Annual Security Awareness",
            "training_date": "2025-02-01",
            "assigned_date": "2025-01-15",
            "completion_date": "2025-01-20",
            "completion_status": "completed",
            "score": 96,
            "valid_until": "2026-01-20",
            "validity_period": "365d",
            "expiry_date": "2026-01-20",
            "mandatory_training": True,
            "secure_coding_training": False,
            "ai_safety_training": False,
            "onboarding_training_completed": True,
            "verified": True,
            "overdue": False,
            "compliance_status": "compliant",
            "created_time": now,
            "last_updated_time": now,
        },
        {
            "record_id": "TRN-3002",
            "employee_id": "EMP-1002",
            "employee_name": "Mina Flores",
            "department": "Engineering",
            "role": "AI Developer",
            "hire_date": "2023-08-01",
            "training_id": "AI-201",
            "training_name": "AI Safety and Responsible Development",
            "training_date": "2025-03-15",
            "assigned_date": "2025-03-01",
            "completion_date": "2025-03-10",
            "completion_status": "completed",
            "score": 92,
            "valid_until": "2026-03-10",
            "validity_period": "365d",
            "expiry_date": "2026-03-10",
            "mandatory_training": True,
            "secure_coding_training": True,
            "ai_safety_training": True,
            "onboarding_training_completed": True,
            "verified": True,
            "overdue": False,
            "compliance_status": "compliant",
            "created_time": now,
            "last_updated_time": now,
        },
    ]


def get_background_checks(configuration_data: dict[str, Any]) -> list[dict[str, Any]]:
    now = _iso_now()
    return [
        {
            "record_id": "BGC-4001",
            "employee_id": "EMP-1001",
            "employee_name": "Avery Chen",
            "contractor_id": "",
            "contractor_name": "",
            "employment_type": "full_time",
            "engagement_type": "",
            "background_check_required": True,
            "background_check_completed": True,
            "verification_status": "verified",
            "verification_type": "identity_and_employment",
            "verification_provider": "Sterling",
            "verification_date": "2024-01-10",
            "result": "clear",
            "cleared_for_hire": True,
            "approved_for_engagement": False,
            "created_time": now,
            "last_updated_time": now,
        },
        {
            "record_id": "BGC-4002",
            "employee_id": "",
            "employee_name": "",
            "contractor_id": "CTR-501",
            "contractor_name": "Riya Das",
            "employment_type": "",
            "engagement_type": "vendor_contractor",
            "background_check_required": True,
            "background_check_completed": True,
            "verification_status": "verified",
            "verification_type": "identity_and_criminal",
            "verification_provider": "FirstAdvantage",
            "verification_date": "2025-02-12",
            "result": "clear",
            "cleared_for_hire": False,
            "approved_for_engagement": True,
            "created_time": now,
            "last_updated_time": now,
        },
    ]


def get_documents(configuration_data: dict[str, Any]) -> list[dict[str, Any]]:
    now = _iso_now()
    return [
        {
            "record_id": "DOC-5001",
            "employee_id": "EMP-1001",
            "employee_name": "Avery Chen",
            "contractor_id": "",
            "contractor_name": "",
            "document_id": "HB-2025",
            "document_name": "Employee Handbook",
            "agreement_id": "CA-2025-EMP-1001",
            "agreement_version": "v3.1",
            "acknowledged": True,
            "acknowledgment_date": "2025-01-16",
            "acknowledgement_version": "v2025.1",
            "signed": True,
            "signature_date": "2025-01-16",
            "effective_date": "2025-01-16",
            "access_granted_after_signing": True,
            "document_status": "active",
            "verified": True,
            "created_time": now,
            "last_updated_time": now,
        },
        {
            "record_id": "DOC-5002",
            "employee_id": "",
            "employee_name": "",
            "contractor_id": "CTR-501",
            "contractor_name": "Riya Das",
            "document_id": "CA-CTR-501",
            "document_name": "Contractor Confidentiality Agreement",
            "agreement_id": "CA-2025-CTR-501",
            "agreement_version": "v2.0",
            "acknowledged": True,
            "acknowledgment_date": "2025-02-20",
            "acknowledgement_version": "v2.0",
            "signed": True,
            "signature_date": "2025-02-20",
            "effective_date": "2025-02-20",
            "access_granted_after_signing": True,
            "document_status": "active",
            "verified": True,
            "created_time": now,
            "last_updated_time": now,
        },
    ]


def get_roles(configuration_data: dict[str, Any]) -> list[dict[str, Any]]:
    company = configuration_data.get("company_name", "Acme Corp")
    now = _iso_now()
    return [
        {
            "record_id": "ROLE-6001",
            "employee_id": "EMP-1001",
            "employee_name": "Avery Chen",
            "role_id": "ROLE-SEC-01",
            "role_name": "Security Officer",
            "role_title": "Security Officer",
            "role_type": "governance",
            "privacy_officer_or_dpo": "Security Officer",
            "department": "Information Security",
            "job_title": "Security Officer",
            "role_description": "Owns security governance, monitoring, and compliance coordination.",
            "responsibilities": "Risk assessments, policy governance, security operations oversight.",
            "responsibilities_defined": True,
            "authority_defined": True,
            "reporting_structure_defined": True,
            "required_qualifications": ["CISSP", "5+ years security leadership"],
            "status": "active",
            "approved_by": "CEO",
            "document_id": "ORG-2025",
            "organization_name": company,
            "version": "v5",
            "document_status": "approved",
            "departments_defined": True,
            "executive_roles_identified": True,
            "department_heads_assigned": True,
            "effective_date": "2025-01-01",
            "last_reviewed_date": "2025-12-01",
            "reporting_manager_role": "Chief Executive Officer",
            "document_version": "v5",
            "approved_on": "2025-01-01",
            "employment_type": "full_time",
            "reporting_manager": "Jordan Patel",
            "reporting_manager_id": "EMP-1000",
            "reporting_manager_name": "Jordan Patel",
            "employment_status": "active",
            "board_member_id": "BRD-01",
            "board_member_name": "Elena Morris",
            "affiliation": "Independent",
            "independent_director": True,
            "conflict_of_interest_declared": True,
            "tenure_start_date": "2023-01-01",
            "tenure_end_date": "2027-12-31",
            "committee_memberships": ["Audit Committee", "Risk Committee"],
            "voting_rights": "full",
            "compliance_status": "compliant",
            "professional_background": "Cybersecurity executive",
            "years_of_experience": 18,
            "industry_experience": "SaaS, financial services",
            "technology_expertise": "Cloud security, GRC",
            "certifications": ["CISSP", "CISM"],
            "current_affiliations": ["TechGov Council"],
            "relevant_experience_summary": "Led enterprise security programs across regulated sectors.",
            "qualification_verified": True,
            "appointment_status": "active",
            "appointed_by": "Board Chair",
            "appointment_date": "2024-01-01",
            "responsibilities_assigned": True,
            "assigned_date": "2025-01-02",
            "assignment_status": "active",
            "last_review_date": "2025-12-01",
            "ai_risk_management_role": True,
            "register_id": "REG-01",
            "privilege_level": "high",
            "assigned_users": ["EMP-1001", "EMP-1003"],
            "role_owner": "Jordan Patel",
            "last_reviewed_time": now,
            "created_time": now,
            "last_updated_time": now,
        }
    ]


def get_policy_ack(configuration_data: dict[str, Any]) -> list[dict[str, Any]]:
    now = _iso_now()
    return [
        {
            "record_id": "POL-7001",
            "employee_id": "EMP-1001",
            "employee_name": "Avery Chen",
            "policy_id": "POL-IS-01",
            "policy_name": "Information Security Policy",
            "policy_version": "v4.2",
            "acknowledged": True,
            "acknowledgement_date": "2025-01-16",
            "acknowledgment_date": "2025-01-16",
            "acknowledgement_method": "portal_acknowledgement",
            "acknowledgment_method": "portal_acknowledgement",
            "mandatory": True,
            "status": "completed",
            "verified": True,
            "created_time": now,
            "last_updated_time": now,
        }
    ]
