from __future__ import annotations

import json
from typing import Any


DARWINBOX_EVIDENCE_SCHEMAS: list[dict[str, Any]] = [
    {
        "code": "EV-25",
        "name": "Employee Termination Records",
        "category": "HRMS",
        "source": "terminations",
        "api": "mock://darwinbox/terminations",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "employment_type": "",
            "department": "",
            "termination_date": "",
            "termination_reason": "",
            "termination_status": "",
            "last_working_day": "",
            "record_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-26",
        "name": "Employee Offboarding Checklist Records",
        "category": "HRMS",
        "source": "terminations",
        "api": "mock://darwinbox/terminations",
        "required_fields": {
            "checklist_id": "",
            "employee_id": "",
            "employee_name": "",
            "termination_date": "",
            "asset_return_completed": True,
            "access_revocation_completed": True,
            "knowledge_transfer_completed": True,
            "user_accounts_disabled": True,
            "checklist_status": "",
            "completed_by": "",
            "completed_date": "",
        },
    },
    {
        "code": "EV-69",
        "name": "Security Officer Job Description",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "job_description_id": "",
            "role_name": "",
            "department": "",
            "responsibilities_defined": True,
            "authority_defined": True,
            "reporting_structure_defined": True,
            "required_qualifications": [],
            "status": "",
            "approved_by": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-88",
        "name": "Security Awareness Training Records",
        "category": "HRMS",
        "source": "trainings",
        "api": "mock://darwinbox/trainings",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "department": "",
            "training_id": "",
            "training_name": "",
            "training_date": "",
            "assigned_date": "",
            "completion_date": "",
            "completion_status": "",
            "score": "",
            "valid_until": "",
            "overdue": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-89",
        "name": "Employee Onboarding Training Records",
        "category": "HRMS",
        "source": "trainings",
        "api": "mock://darwinbox/trainings",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "hire_date": "",
            "onboarding_training_completed": True,
            "training_id": "",
            "training_name": "",
            "completion_date": "",
            "completion_status": "",
            "mandatory_training": True,
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-113",
        "name": "Employee Background Verification Records",
        "category": "HRMS",
        "source": "background_checks",
        "api": "mock://darwinbox/background_checks",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "employment_type": "",
            "background_check_required": True,
            "background_check_completed": True,
            "verification_status": "",
            "verification_type": "",
            "verification_provider": "",
            "verification_date": "",
            "result": "",
            "cleared_for_hire": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-114",
        "name": "Contractor Background Verification Records",
        "category": "HRMS",
        "source": "background_checks",
        "api": "mock://darwinbox/background_checks",
        "required_fields": {
            "record_id": "",
            "contractor_id": "",
            "contractor_name": "",
            "engagement_type": "",
            "background_check_required": True,
            "background_check_completed": True,
            "verification_status": "",
            "verification_type": "",
            "verification_provider": "",
            "verification_date": "",
            "result": "",
            "approved_for_engagement": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-119",
        "name": "Employee Handbook Acknowledgement Records",
        "category": "HRMS",
        "source": "documents",
        "api": "mock://darwinbox/documents",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "document_id": "",
            "document_name": "",
            "acknowledged": True,
            "acknowledgment_date": "",
            "acknowledgement_version": "",
            "status": "",
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-121",
        "name": "Employee Disciplinary Action Records",
        "category": "HRMS",
        "source": "employees",
        "api": "mock://darwinbox/employees",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "violation_type": "",
            "policy_violated": "",
            "incident_date": "",
            "investigation_conducted": True,
            "investigation_details": "",
            "disciplinary_action_taken": "",
            "action_severity": "",
            "approved_by": "",
            "action_date": "",
            "status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-128",
        "name": "Organizational Chart",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "document_id": "",
            "organization_name": "",
            "version": "",
            "document_status": "",
            "departments_defined": True,
            "reporting_structure_defined": True,
            "executive_roles_identified": True,
            "department_heads_assigned": True,
            "effective_date": "",
            "last_reviewed_date": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-129",
        "name": "Employee Role and Responsibility Records",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "department": "",
            "job_title": "",
            "role_description": "",
            "responsibilities_defined": True,
            "reporting_manager_id": "",
            "reporting_manager_name": "",
            "employment_status": "",
            "effective_date": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-130",
        "name": "Employee Confidentiality Agreement Records",
        "category": "HRMS",
        "source": "documents",
        "api": "mock://darwinbox/documents",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "agreement_id": "",
            "agreement_version": "",
            "signed": True,
            "signature_date": "",
            "effective_date": "",
            "access_granted_after_signing": True,
            "document_status": "",
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-131",
        "name": "Contractor Confidentiality Agreement Records",
        "category": "HRMS",
        "source": "documents",
        "api": "mock://darwinbox/documents",
        "required_fields": {
            "record_id": "",
            "contractor_id": "",
            "contractor_name": "",
            "agreement_id": "",
            "agreement_version": "",
            "signed": True,
            "signature_date": "",
            "effective_date": "",
            "access_granted_after_signing": True,
            "document_status": "",
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-136",
        "name": "Employee Performance Review Records",
        "category": "HRMS",
        "source": "employees",
        "api": "mock://darwinbox/employees",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "review_cycle": "",
            "self_review_completed": True,
            "manager_review_completed": True,
            "review_date": "",
            "performance_rating": "",
            "feedback_provided": True,
            "review_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-137",
        "name": "Employee Probation Review Records",
        "category": "HRMS",
        "source": "employees",
        "api": "mock://darwinbox/employees",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "hire_date": "",
            "probation_review_required": True,
            "probation_review_completed": True,
            "review_date": "",
            "evaluation_result": "",
            "manager_id": "",
            "review_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-140",
        "name": "Employee Policy Acknowledgement Records",
        "category": "HRMS",
        "source": "policy_ack",
        "api": "mock://darwinbox/policy_ack",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "policy_id": "",
            "policy_name": "",
            "policy_version": "",
            "acknowledged": True,
            "acknowledgement_date": "",
            "acknowledgement_method": "",
            "mandatory": True,
            "status": "",
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-144",
        "name": "Candidate Interview Evaluation Records",
        "category": "HRMS",
        "source": "employees",
        "api": "mock://darwinbox/employees",
        "required_fields": {
            "record_id": "",
            "candidate_id": "",
            "candidate_name": "",
            "position_applied": "",
            "interview_stage": "",
            "interviewer_id": "",
            "interviewer_name": "",
            "evaluation_score": "",
            "feedback": "",
            "decision": "",
            "decision_date": "",
            "hiring_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-146",
        "name": "Job Description Documents",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "document_id": "",
            "job_title": "",
            "department": "",
            "role_description": "",
            "responsibilities": "",
            "required_qualifications": "",
            "reporting_manager_role": "",
            "employment_type": "",
            "document_version": "",
            "document_status": "",
            "approved_on": "",
            "effective_date": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-160",
        "name": "Acceptable Use Policy Acknowledgement Records",
        "category": "HRMS",
        "source": "policy_ack",
        "api": "mock://darwinbox/policy_ack",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "policy_id": "",
            "policy_version": "",
            "acknowledged": True,
            "acknowledgment_date": "",
            "acknowledgment_method": "",
            "mandatory": True,
            "status": "",
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-227",
        "name": "Board Composition Records",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "record_id": "",
            "board_member_id": "",
            "board_member_name": "",
            "role": "",
            "employment_status": "",
            "affiliation": "",
            "independent_director": True,
            "conflict_of_interest_declared": True,
            "tenure_start_date": "",
            "tenure_end_date": "",
            "committee_memberships": [],
            "voting_rights": "",
            "compliance_status": "",
        },
    },
    {
        "code": "EV-230",
        "name": "Board Member Qualification Records",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "record_id": "",
            "board_member_id": "",
            "board_member_name": "",
            "role": "",
            "professional_background": "",
            "years_of_experience": 0,
            "industry_experience": "",
            "technology_expertise": "",
            "certifications": [],
            "current_affiliations": [],
            "relevant_experience_summary": "",
            "qualification_verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-292",
        "name": "Employee Training Records",
        "category": "HRMS",
        "source": "trainings",
        "api": "mock://darwinbox/trainings",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "role": "",
            "department": "",
            "training_id": "",
            "training_name": "",
            "mandatory_training": True,
            "assigned_date": "",
            "completion_status": "",
            "completion_date": "",
            "score": "",
            "validity_period": "",
            "expiry_date": "",
            "compliance_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-317",
        "name": "Secure Coding Training Records",
        "category": "HRMS",
        "source": "trainings",
        "api": "mock://darwinbox/trainings",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "role": "",
            "department": "",
            "training_id": "",
            "training_name": "",
            "secure_coding_training": True,
            "assigned_date": "",
            "completion_status": "",
            "completion_date": "",
            "score": "",
            "validity_period": "",
            "expiry_date": "",
            "compliance_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-337",
        "name": "Privacy Officer Appointment Records",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "role_title": "",
            "role_type": "",
            "privacy_officer_or_dpo": "",
            "department": "",
            "appointment_status": "",
            "appointed_by": "",
            "appointment_date": "",
            "responsibilities_assigned": True,
            "reporting_manager": "",
            "tenure_start_date": "",
            "tenure_end_date": "",
        },
    },
    {
        "code": "EV-402",
        "name": "Team Role Assignment Records",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "role_id": "",
            "role_name": "",
            "ai_risk_management_role": True,
            "department": "",
            "assigned_date": "",
            "responsibilities": "",
            "reporting_manager": "",
            "assignment_status": "",
            "last_review_date": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-417",
        "name": "AI Development Training Records",
        "category": "HRMS",
        "source": "trainings",
        "api": "mock://darwinbox/trainings",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "role": "",
            "department": "",
            "training_id": "",
            "training_name": "",
            "ai_safety_training": True,
            "assigned_date": "",
            "completion_status": "",
            "completion_date": "",
            "score": "",
            "validity_period": "",
            "expiry_date": "",
            "compliance_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-521",
        "name": "Role and Responsibility Register",
        "category": "HRMS",
        "source": "roles",
        "api": "mock://darwinbox/roles",
        "required_fields": {
            "register_id": "",
            "role_id": "",
            "role_name": "",
            "responsibilities": "",
            "privilege_level": "",
            "assigned_users": [],
            "role_owner": "",
            "status": "",
            "last_reviewed_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
    {
        "code": "EV-564",
        "name": "Employee Disclosure Check Records",
        "category": "HRMS",
        "source": "employees",
        "api": "mock://darwinbox/employees",
        "required_fields": {
            "record_id": "",
            "employee_id": "",
            "employee_name": "",
            "references": "",
            "contact_number": "",
            "relation": "",
            "disclosed_to": "",
            "created_time": "",
            "last_updated_time": "",
        },
    },
]

EVIDENCE_MASTER_NAME_ORDER: tuple[str, ...] = tuple(row["name"] for row in DARWINBOX_EVIDENCE_SCHEMAS)
CODE_TO_SCHEMA: dict[str, dict[str, Any]] = {row["code"]: row for row in DARWINBOX_EVIDENCE_SCHEMAS}


def schema_description(row: dict[str, Any]) -> str:
    return json.dumps(row["required_fields"], sort_keys=True)
