from __future__ import annotations

import json
from typing import Any


def _schema(
    code: str,
    name: str,
    source: str,
    table: str,
    required_fields: dict[str, Any],
) -> dict[str, Any]:
    return {
        "code": code,
        "name": name,
        "category": "ITSM",
        "source": source,
        "table": table,
        "api": f"/api/now/table/{table}",
        "required_fields": required_fields,
    }


SERVICENOW_EVIDENCE_SCHEMAS: list[dict[str, Any]] = [
    _schema(
        "EV-5",
        "Backup Failure Incident Tickets",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "system_id": "",
            "system_name": "",
            "incident_type": "",
            "failure_detected_time": "",
            "reported_time": "",
            "resolution_time": "",
            "status": "",
            "root_cause": "",
            "resolution_details": "",
            "resolved": True,
            "assigned_to": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-13",
        "AI Model Training Data Approval Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "request_id": "",
            "dataset_id": "",
            "dataset_name": "",
            "data_classification": "",
            "contains_customer_data": True,
            "approval_required": True,
            "approval_status": "",
            "approved_by": "",
            "requested_by": "",
            "request_time": "",
            "approval_time": "",
            "approved_time": "",
            "review_comments": "",
        },
    ),
    _schema(
        "EV-18",
        "Asset Provisioning Tickets",
        "assets",
        "alm_asset",
        {
            "ticket_id": "",
            "asset_id": "",
            "asset_name": "",
            "request_type": "",
            "provisioning_status": "",
            "approved": True,
            "requested_by": "",
            "approved_by": "",
            "provisioned_by": "",
            "request_time": "",
            "approval_time": "",
            "provisioning_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-19",
        "Asset Decommissioning Tickets",
        "assets",
        "alm_asset",
        {
            "ticket_id": "",
            "asset_id": "",
            "asset_name": "",
            "decommission_status": "",
            "decommission_approved": True,
            "requested_by": "",
            "approved_by": "",
            "decommissioned_by": "",
            "request_time": "",
            "approval_time": "",
            "decommission_time": "",
            "reason": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-27",
        "Access Revocation Tickets",
        "tasks",
        "task",
        {
            "ticket_id": "",
            "employee_id": "",
            "employee_name": "",
            "system_id": "",
            "system_name": "",
            "access_type": "",
            "revocation_requested_time": "",
            "revocation_completed_time": "",
            "revoked": True,
            "status": "",
            "performed_by": "",
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-31",
        "Security Incident Register",
        "incidents",
        "incident",
        {
            "incident_id": "",
            "incident_title": "",
            "incident_category": "",
            "severity": "",
            "reported_time": "",
            "detected_time": "",
            "status": "",
            "impact": "",
            "affected_systems": [],
            "resolution_summary": "",
            "closure_time": "",
            "record_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-32",
        "Incident Management Ticket Records",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "incident_id": "",
            "incident_title": "",
            "severity": "",
            "status": "",
            "reported_time": "",
            "assigned_to": "",
            "response_actions": [],
            "containment_actions": [],
            "eradication_actions": [],
            "recovery_actions": [],
            "resolution_time": "",
            "resolved": True,
            "closure_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-35",
        "Access Request Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "request_id": "",
            "user_id": "",
            "user_name": "",
            "system_id": "",
            "system_name": "",
            "access_type": "",
            "requested_role": "",
            "justification": "",
            "request_status": "",
            "requested_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-36",
        "Access Approval Records",
        "requests",
        "sc_request",
        {
            "approval_id": "",
            "ticket_id": "",
            "request_id": "",
            "user_id": "",
            "system_id": "",
            "approved": True,
            "approver_id": "",
            "approver_role": "",
            "approval_time": "",
            "approval_status": "",
            "comments": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-38",
        "Corrective Action Tracking Tickets",
        "tasks",
        "task",
        {
            "ticket_id": "",
            "incident_id": "",
            "action_id": "",
            "action_description": "",
            "priority": "",
            "assigned_to": "",
            "status": "",
            "due_date": "",
            "completion_date": "",
            "completed": True,
            "verification_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-51",
        "Security Alert Investigation Tickets",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "alert_id": "",
            "event_id": "",
            "severity": "",
            "alert_type": "",
            "investigation_status": "",
            "assigned_to": "",
            "investigation_details": "",
            "triage_decision": "",
            "escalated": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-58",
        "Static Code Analysis Vulnerability Tracking Tickets",
        "problems",
        "problem",
        {
            "ticket_id": "",
            "vulnerability_id": "",
            "repository_id": "",
            "severity": "",
            "status": "",
            "assigned_to": "",
            "remediation_action": "",
            "due_date": "",
            "resolution_date": "",
            "resolved": True,
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-62",
        "Vendor Onboarding Approval Records",
        "requests",
        "sc_request",
        {
            "record_id": "",
            "vendor_id": "",
            "vendor_name": "",
            "request_id": "",
            "approval_required": True,
            "approval_status": "",
            "approved_by": "",
            "requested_by": "",
            "request_date": "",
            "approval_date": "",
            "onboarding_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-71",
        "Change Management Tickets",
        "changes",
        "change_request",
        {
            "ticket_id": "",
            "change_id": "",
            "change_type": "",
            "system_id": "",
            "system_name": "",
            "requested_by": "",
            "change_description": "",
            "risk_level": "",
            "impact_assessment": "",
            "request_status": "",
            "requested_time": "",
            "planned_start_time": "",
            "planned_end_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-72",
        "Change Approval Records",
        "changes",
        "change_request",
        {
            "approval_id": "",
            "change_id": "",
            "ticket_id": "",
            "approved": True,
            "approver_id": "",
            "approver_role": "",
            "approval_time": "",
            "approval_status": "",
            "segregation_of_duties_verified": True,
            "comments": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-99",
        "Vulnerability Remediation Tickets",
        "problems",
        "problem",
        {
            "ticket_id": "",
            "vulnerability_id": "",
            "application_id": "",
            "severity": "",
            "status": "",
            "assigned_to": "",
            "remediation_action": "",
            "resolved": True,
            "verified": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-102",
        "Change Management / Deployment Approval Records",
        "changes",
        "change_request",
        {
            "approval_id": "",
            "change_id": "",
            "release_id": "",
            "system_id": "",
            "approved": True,
            "approver_id": "",
            "approver_role": "",
            "approval_time": "",
            "approval_status": "",
            "pre_deployment_approval": True,
            "comments": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-106",
        "Change Request Tickets",
        "changes",
        "change_request",
        {
            "ticket_id": "",
            "change_id": "",
            "request_type": "",
            "system_id": "",
            "system_name": "",
            "requested_by": "",
            "business_justification": "",
            "priority": "",
            "status": "",
            "requested_time": "",
            "approval_required": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-145",
        "Access Request and Approval Records",
        "requests",
        "sc_request",
        {
            "record_id": "",
            "request_id": "",
            "ticket_id": "",
            "user_id": "",
            "user_name": "",
            "system_id": "",
            "system_name": "",
            "requested_role": "",
            "business_justification": "",
            "approved": True,
            "approver_id": "",
            "approver_role": "",
            "approval_time": "",
            "approval_status": "",
            "provisioned": True,
            "provisioning_time": "",
        },
    ),
    _schema(
        "EV-147",
        "Access Revocation Ticket Records",
        "tasks",
        "task",
        {
            "ticket_id": "",
            "user_id": "",
            "system_id": "",
            "access_role": "",
            "issue_identified": "",
            "revocation_required": True,
            "revocation_completed": True,
            "revocation_time": "",
            "status": "",
            "assigned_to": "",
            "resolution_details": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-153",
        "Data Subject Request Ticket Records",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "request_id": "",
            "request_type": "",
            "data_subject_id": "",
            "data_subject_name": "",
            "request_submission_date": "",
            "identity_verified": True,
            "system_scope": "",
            "approval_status": "",
            "approved_by": "",
            "processing_status": "",
            "completion_date": "",
            "sla_met": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-159",
        "Production Data Access Approval Records",
        "requests",
        "sc_request",
        {
            "record_id": "",
            "request_id": "",
            "ticket_id": "",
            "requester_id": "",
            "requester_name": "",
            "data_scope": "",
            "purpose": "",
            "sanitization_required": True,
            "anonymization_required": True,
            "approved": True,
            "approver_id": "",
            "approval_time": "",
            "approval_status": "",
            "data_transfer_allowed": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-213",
        "Customer Support Ticket Records",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "customer_id": "",
            "customer_name": "",
            "ticket_type": "",
            "issue_category": "",
            "issue_description": "",
            "reported_channel": "",
            "priority": "",
            "status": "",
            "assigned_to": "",
            "escalation_required": True,
            "sla_response_time": "",
            "sla_resolution_time": "",
            "response_time_actual": "",
            "resolution_time_actual": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-220",
        "Corrective Action Tickets",
        "tasks",
        "task",
        {
            "ticket_id": "",
            "control_id": "",
            "control_name": "",
            "issue_description": "",
            "issue_severity": "",
            "identified_date": "",
            "assigned_to": "",
            "control_owner": "",
            "remediation_action": "",
            "priority": "",
            "status": "",
            "sla_due_date": "",
            "remediation_start_time": "",
            "remediation_end_time": "",
        },
    ),
    _schema(
        "EV-221",
        "Corrective Action Tracking Reports",
        "tasks",
        "task",
        {
            "report_id": "",
            "report_name": "",
            "reporting_period_start": "",
            "reporting_period_end": "",
            "total_actions_count": 0,
            "open_actions_count": 0,
            "in_progress_actions_count": 0,
            "closed_actions_count": 0,
            "overdue_actions_count": 0,
            "high_severity_actions_count": 0,
            "remediation_progress_tracked": True,
        },
    ),
    _schema(
        "EV-229",
        "Incident Management Tickets",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "incident_id": "",
            "incident_title": "",
            "incident_description": "",
            "incident_category": "",
            "incident_severity": "",
            "reported_by": "",
            "assigned_to": "",
            "status": "",
            "impact": "",
            "root_cause_identified": True,
            "investigation_summary": "",
            "remediation_required": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-270",
        "Data Subject Appeal Records",
        "requests",
        "sc_request",
        {
            "appeal_id": "",
            "data_subject_id": "",
            "data_subject_identifier": "",
            "original_decision_id": "",
            "appeal_reason": "",
            "appeal_submission_date": "",
            "appeal_status": "",
            "assigned_to": "",
            "review_outcome": "",
            "decision_reversed": True,
            "response_provided": True,
            "response_date": "",
            "resolution_summary": "",
        },
    ),
    _schema(
        "EV-274",
        "DSAR Request Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "data_subject_id": "",
            "data_subject_identifier": "",
            "request_type": "",
            "request_description": "",
            "request_submission_date": "",
            "identity_verified": True,
            "assigned_to": "",
            "priority": "",
            "status": "",
            "sla_due_date": "",
            "processing_start_time": "",
            "processing_end_time": "",
            "escalation_required": True,
        },
    ),
    _schema(
        "EV-277",
        "DSAR Request Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "data_subject_id": "",
            "data_subject_identifier": "",
            "request_type": "",
            "request_description": "",
            "request_submission_date": "",
            "identity_verified": True,
            "assigned_to": "",
            "priority": "",
            "status": "",
            "sla_due_date": "",
            "processing_start_time": "",
            "processing_end_time": "",
            "escalation_required": True,
        },
    ),
    _schema(
        "EV-278",
        "DSAR Fulfillment Records",
        "requests",
        "sc_request",
        {
            "record_id": "",
            "ticket_id": "",
            "data_subject_id": "",
            "response_type": "",
            "data_provided": "",
            "modifications_applied": True,
            "response_sent": True,
            "response_date": "",
            "response_method": "",
            "approval_status": "",
            "approved_by": "",
            "compliance_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-324",
        "Emergency Change Tickets",
        "changes",
        "change_request",
        {
            "ticket_id": "",
            "change_id": "",
            "change_title": "",
            "change_description": "",
            "change_type": "emergency",
            "system_id": "",
            "requested_by": "",
            "approval_status": "",
            "approved_by": "",
            "approval_time": "",
            "implementation_start_time": "",
            "implementation_status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-325",
        "Emergency Change Review Records",
        "changes",
        "change_request",
        {
            "review_id": "",
            "change_id": "",
            "ticket_id": "",
            "review_date": "",
            "reviewed_by": "",
            "change_outcome": "",
            "issues_identified": True,
            "issue_details": "",
            "compliance_with_process": True,
            "corrective_actions_defined": True,
            "approval_status": "",
            "approved_by": "",
            "next_review_date": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-329",
        "Customer Complaint Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "customer_id": "",
            "customer_identifier": "",
            "complaint_category": "",
            "complaint_description": "",
            "submission_date": "",
            "reported_by": "",
            "assigned_to": "",
            "priority": "",
            "status": "",
            "investigation_started": True,
            "sla_due_date": "",
            "resolution_status": "",
            "resolution_details": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-330",
        "Complaint Resolution Records",
        "requests",
        "sc_request",
        {
            "record_id": "",
            "ticket_id": "",
            "investigation_summary": "",
            "root_cause_identified": True,
            "resolution_action": "",
            "resolution_date": "",
            "customer_notified": True,
            "customer_notification_date": "",
            "customer_satisfaction_status": "",
            "escalation_required": True,
            "approval_status": "",
            "approved_by": "",
        },
    ),
    _schema(
        "EV-338",
        "Customer Feedback / Complaint Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "customer_id": "",
            "customer_identifier": "",
            "feedback_type": "",
            "feedback_category": "",
            "feedback_description": "",
            "submission_date": "",
            "submission_channel": "",
            "assigned_to": "",
            "priority": "",
            "status": "",
            "response_provided": True,
            "response_date": "",
            "resolution_status": "",
            "resolution_details": "",
        },
    ),
    _schema(
        "EV-347",
        "Internal Support Tickets",
        "tasks",
        "task",
        {
            "ticket_id": "",
            "employee_id": "",
            "employee_name": "",
            "department": "",
            "issue_type": "",
            "issue_category": "",
            "issue_description": "",
            "reported_date": "",
            "reported_channel": "",
            "assigned_to": "",
            "priority": "",
            "status": "",
            "investigation_started": True,
            "resolution_status": "",
            "resolution_details": "",
        },
    ),
    _schema(
        "EV-351",
        "AI Incident Management Tickets",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "incident_id": "",
            "ai_system_id": "",
            "ai_system_name": "",
            "incident_type": "",
            "incident_description": "",
            "incident_severity": "",
            "reported_by": "",
            "reported_time": "",
            "assigned_to": "",
            "status": "",
            "investigation_started": True,
            "root_cause_identified": True,
            "remediation_action": "",
            "resolution_time": "",
        },
    ),
    _schema(
        "EV-373",
        "User Behavior Investigation Tickets",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "alert_id": "",
            "user_id": "",
            "user_identifier": "",
            "incident_description": "",
            "incident_severity": "",
            "reported_time": "",
            "assigned_to": "",
            "status": "",
            "investigation_started": True,
            "root_cause_identified": True,
            "remediation_action": "",
            "remediation_status": "",
            "resolution_time": "",
        },
    ),
    _schema(
        "EV-381",
        "Personal Data Correction Requests",
        "requests",
        "sc_request",
        {
            "request_id": "",
            "ticket_id": "",
            "data_subject_id": "",
            "data_subject_identifier": "",
            "request_type": "correction",
            "requested_fields": [],
            "request_description": "",
            "submitted_date": "",
            "verification_status": "",
            "verified_by": "",
            "assigned_to": "",
            "status": "",
            "resolution_status": "",
            "resolution_date": "",
        },
    ),
    _schema(
        "EV-387",
        "Public Content Approval Records",
        "requests",
        "sc_request",
        {
            "record_id": "",
            "content_id": "",
            "content_title": "",
            "content_type": "",
            "submitted_by": "",
            "reviewed_by": "",
            "review_date": "",
            "confidentiality_check_passed": True,
            "approval_status": "",
            "approved_by": "",
            "approval_date": "",
            "publication_date": "",
            "comments": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-394",
        "Insider Threat Investigation Tickets",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "alert_id": "",
            "user_id": "",
            "user_identifier": "",
            "ai_system_id": "",
            "ai_system_name": "",
            "incident_description": "",
            "incident_severity": "",
            "reported_time": "",
            "assigned_to": "",
            "investigation_started": True,
            "root_cause_identified": True,
            "misuse_confirmed": True,
            "remediation_action": "",
            "resolution_time": "",
        },
    ),
    _schema(
        "EV-408",
        "Customer Engagement Activity Records",
        "requests",
        "sc_request",
        {
            "record_id": "",
            "customer_id": "",
            "customer_name": "",
            "engagement_type": "",
            "communication_channel": "",
            "engagement_date": "",
            "conducted_by": "",
            "summary": "",
            "follow_up_required": True,
            "next_engagement_date": "",
            "status": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-414",
        "Incident Notification Records",
        "incidents",
        "incident",
        {
            "record_id": "",
            "incident_id": "",
            "service_name": "",
            "incident_type": "",
            "notification_type": "",
            "communication_channel": "",
            "message_summary": "",
            "sent_to": [],
            "acknowledged_status": "",
            "follow_up_required": True,
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-437",
        "Customer Feedback Records",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "customer_id": "",
            "feedback_type": "",
            "feedback_description": "",
            "ai_system_reference": "",
            "feedback_category": "",
            "reported_time": "",
            "status": "",
            "resolution_action": "",
            "resolved_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-444",
        "AI Concern Reporting Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "reported_by": "",
            "reporter_type": "",
            "ai_system_reference": "",
            "concern_category": "",
            "concern_description": "",
            "reported_time": "",
            "priority": "",
            "status": "",
            "assigned_to": "",
            "resolution_action": "",
            "resolution_status": "",
            "resolution_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-473",
        "Security Incident Tickets",
        "incidents",
        "incident",
        {
            "ticket_id": "",
            "incident_id": "",
            "threat_reference": "",
            "incident_description": "",
            "detected_time": "",
            "severity": "",
            "status": "",
            "assigned_to": "",
            "investigation_actions": [],
            "resolution_actions": [],
            "resolution_status": "",
            "resolved_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-489",
        "Data Disposal Request Tickets",
        "tasks",
        "task",
        {
            "ticket_id": "",
            "requester_id": "",
            "data_type": "",
            "system_id": "",
            "disposal_reason": "",
            "approval_status": "",
            "approved_by": "",
            "request_date": "",
            "execution_status": "",
            "execution_date": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-507",
        "Disaster Recovery Test Tickets",
        "tasks",
        "task",
        {
            "ticket_id": "",
            "test_id": "",
            "test_description": "",
            "scheduled_date": "",
            "execution_status": "",
            "assigned_to": "",
            "test_outcome": "",
            "issues_logged": True,
            "closure_status": "",
            "closed_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-519",
        "Access Review Approval Records",
        "users",
        "sys_user",
        {
            "record_id": "",
            "review_id": "",
            "user_id": "",
            "system_id": "",
            "approval_status": "",
            "approved_by": "",
            "approval_date": "",
            "justification": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-543",
        "Data Subject Access Request Register",
        "requests",
        "sc_request",
        {
            "register_id": "",
            "request_id": "",
            "data_subject_id": "",
            "request_type": "",
            "request_received_date": "",
            "verification_status": "",
            "request_status": "",
            "response_due_date": "",
            "response_date": "",
            "resolution_outcome": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-544",
        "Data Subject Access Request Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "request_id": "",
            "submitted_by": "",
            "request_description": "",
            "priority": "",
            "status": "",
            "assigned_to": "",
            "processing_actions": [],
            "closure_status": "",
            "closed_time": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-554",
        "License Compliance Review Records",
        "assets",
        "alm_asset",
        {
            "record_id": "",
            "sbom_id": "",
            "component_name": "",
            "license_type": "",
            "review_date": "",
            "reviewed_by": "",
            "exception_required": True,
            "approval_status": "",
            "approved_by": "",
            "justification": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
    _schema(
        "EV-568",
        "Third-Party Service Review Tickets",
        "requests",
        "sc_request",
        {
            "ticket_id": "",
            "service_review_id": "",
            "service_name": "",
            "vendor_id": "",
            "review_type": "",
            "requested_by": "",
            "review_status": "",
            "approved_by": "",
            "request_date": "",
            "review_date": "",
            "findings": "",
            "created_time": "",
            "last_updated_time": "",
        },
    ),
]

EVIDENCE_MASTER_NAME_ORDER: tuple[str, ...] = tuple(row["name"] for row in SERVICENOW_EVIDENCE_SCHEMAS)
CODE_TO_SCHEMA: dict[str, dict[str, Any]] = {row["code"]: row for row in SERVICENOW_EVIDENCE_SCHEMAS}


def schema_description(row: dict[str, Any]) -> str:
    return json.dumps(row["required_fields"], sort_keys=True)
