"""
Maps framework ``evidence_masters.code`` values (e.g. EV-105) to Bitbucket collection strategies.

Strategies use Bitbucket Cloud 2.0 REST where data exists; otherwise collectors return
``collectable_via_bitbucket_api: false`` with a short rationale.
"""

from __future__ import annotations

from typing import Literal

# Human titles and API hints for optional seeding (domain-scoped).
DEVOPS_EVIDENCE_SEED_ROWS: list[dict[str, str]] = [
    {"code": "EV-56", "name": "Static Code Analysis Tool Configuration — DevOps", "category": "DevOps", "api": "pipelines / repository"},
    {"code": "EV-57", "name": "Static Code Analysis Scan Reports — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-64", "name": "Product Authentication Configuration Records — DevOps", "category": "DevOps", "api": "repository metadata"},
    {"code": "EV-21", "name": "User Consent Records — DevOps", "category": "DevOps", "api": "issues (if enabled)"},
    {"code": "EV-23", "name": "User Consent Capture Configuration — DevOps", "category": "DevOps", "api": "issues"},
    {"code": "EV-47", "name": "Cloud Infrastructure Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-74", "name": "Production Deployment Logs — DevOps", "category": "DevOps", "api": "deployments"},
    {"code": "EV-65", "name": "Product Access Control Configuration Records — DevOps", "category": "DevOps", "api": "branch restrictions"},
    {"code": "EV-66", "name": "Product Security Testing Reports — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-73", "name": "Code Review Records — DevOps", "category": "DevOps", "api": "pullrequests"},
    {"code": "EV-81", "name": "Infrastructure-as-Code Repository Records — DevOps", "category": "DevOps", "api": "repositories"},
    {"code": "EV-82", "name": "CI/CD Pipeline Configuration Records — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-83", "name": "Infrastructure Deployment Logs — DevOps", "category": "DevOps", "api": "deployments"},
    {"code": "EV-100", "name": "Audit Log Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-103", "name": "Sprint Planning Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-105", "name": "Source Code Repository Records — DevOps", "category": "DevOps", "api": "repositories"},
    {"code": "EV-110", "name": "Security Design Review Records — DevOps", "category": "DevOps", "api": "pullrequests"},
    {"code": "EV-120", "name": "Backup Retention Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-157", "name": "Storage Encryption Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-166", "name": "Backup Storage Location Configuration — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-168", "name": "Data Encryption Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-169", "name": "Application Performance Monitoring Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-172", "name": "Utilization Monitoring Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-416", "name": "Release Approval Records — DevOps", "category": "DevOps", "api": "deployments"},
    {"code": "EV-174", "name": "Key Management System Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-175", "name": "Encryption Key Usage Reports — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-177", "name": "TLS Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-180", "name": "System Hardening Playbooks — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-181", "name": "Infrastructure Build Configuration Records — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-196", "name": "Release Notification Records — DevOps", "category": "DevOps", "api": "deployments"},
    {"code": "EV-201", "name": "Encryption Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-202", "name": "CI/CD Pipeline Execution Logs — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-203", "name": "Automated Test Execution Reports — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-206", "name": "Source Code Repository Configuration Records — DevOps", "category": "DevOps", "api": "repositories"},
    {"code": "EV-208", "name": "Source Code Repository Activity Logs — DevOps", "category": "DevOps", "api": "commits"},
    {"code": "EV-211", "name": "Environment Configuration Records — DevOps", "category": "DevOps", "api": "deployments"},
    {"code": "EV-215", "name": "Documentation Publication Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-233", "name": "Data Retention Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-237", "name": "Infrastructure Configuration Records — DevOps", "category": "DevOps", "api": "repositories"},
    {"code": "EV-240", "name": "VPN Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-259", "name": "AI System Control Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-285", "name": "Privacy Management Tool Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-286", "name": "Privacy Compliance Monitoring Reports — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-318", "name": "Static Code Analysis Reports — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-321", "name": "CI/CD Pipeline Notification Configuration Records — DevOps", "category": "DevOps", "api": "hooks"},
    {"code": "EV-331", "name": "CI/CD Pipeline Access Control Configuration Records — DevOps", "category": "DevOps", "api": "branch restrictions"},
    {"code": "EV-346", "name": "AI Data Preparation Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-356", "name": "API Logging Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-361", "name": "Schema Validation Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-365", "name": "API Documentation Site — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-366", "name": "API Specification Files — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-375", "name": "Data Storage Location Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-379", "name": "Data Masking Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-391", "name": "Authentication System Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-405", "name": "AI Model Validation Reports — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-409", "name": "Privileged Access Management Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-410", "name": "Privileged Access Activity Logs — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-415", "name": "GitHub Pull Request Review Records — DevOps", "category": "DevOps", "api": "pullrequests"},
    {"code": "EV-423", "name": "System Design Review Records — DevOps", "category": "DevOps", "api": "pullrequests"},
    {"code": "EV-426", "name": "AI System Logging Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-439", "name": "AI Model Evaluation Reports — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-453", "name": "AI Test Set Definitions — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-454", "name": "AI Test Execution Reports — DevOps", "category": "DevOps", "api": "pipelines"},
    {"code": "EV-458", "name": "NTP Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-511", "name": "Security Monitoring Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-553", "name": "Software Bill of Materials (SBOM) — DevOps", "category": "DevOps", "api": "pipelines artifacts"},
    {"code": "EV-3", "name": "Backup Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-9", "name": "Data Store Encryption Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-10", "name": "Encryption Key Configuration Records — DevOps", "category": "DevOps", "api": "—"},
    {"code": "EV-104", "name": "Deployment Logs — DevOps", "category": "DevOps", "api": "deployments"},
    {"code": "EV-517", "name": "Project Security Review Records — DevOps", "category": "DevOps", "api": "pullrequests"},
    {"code": "EV-4", "name": "Automated Backup Job Logs — DevOps", "category": "DevOps", "api": "pipelines"},
]

BitbucketStrategy = Literal[
    "repositories",
    "commits",
    "pull_requests",
    "pipelines",
    "deployments",
    "hooks",
    "branch_restrictions",
    "issues",
    "not_applicable",
]

# Which Bitbucket API family backs each evidence code (best-effort).
EVIDENCE_CODE_STRATEGY: dict[str, BitbucketStrategy] = {
    "EV-105": "repositories",
    "EV-206": "repositories",
    "EV-81": "repositories",
    "EV-237": "repositories",
    "EV-208": "commits",
    "EV-73": "pull_requests",
    "EV-415": "pull_requests",
    "EV-110": "pull_requests",
    "EV-423": "pull_requests",
    "EV-517": "pull_requests",
    "EV-82": "pipelines",
    "EV-202": "pipelines",
    "EV-203": "pipelines",
    "EV-318": "pipelines",
    "EV-56": "pipelines",
    "EV-57": "pipelines",
    "EV-66": "pipelines",
    "EV-181": "pipelines",
    "EV-454": "pipelines",
    "EV-4": "pipelines",
    "EV-321": "hooks",
    "EV-104": "deployments",
    "EV-74": "deployments",
    "EV-83": "deployments",
    "EV-416": "deployments",
    "EV-196": "deployments",
    "EV-211": "deployments",
    "EV-65": "branch_restrictions",
    "EV-331": "branch_restrictions",
    "EV-21": "issues",
    "EV-23": "issues",
    "EV-553": "pipelines",
    "EV-64": "not_applicable",
    "EV-47": "not_applicable",
    "EV-100": "not_applicable",
    "EV-103": "not_applicable",
    "EV-120": "not_applicable",
    "EV-157": "not_applicable",
    "EV-166": "not_applicable",
    "EV-168": "not_applicable",
    "EV-169": "not_applicable",
    "EV-172": "not_applicable",
    "EV-174": "not_applicable",
    "EV-175": "not_applicable",
    "EV-177": "not_applicable",
    "EV-180": "not_applicable",
    "EV-201": "not_applicable",
    "EV-215": "not_applicable",
    "EV-233": "not_applicable",
    "EV-240": "not_applicable",
    "EV-259": "not_applicable",
    "EV-285": "not_applicable",
    "EV-286": "not_applicable",
    "EV-346": "not_applicable",
    "EV-356": "not_applicable",
    "EV-361": "not_applicable",
    "EV-365": "not_applicable",
    "EV-366": "not_applicable",
    "EV-375": "not_applicable",
    "EV-379": "not_applicable",
    "EV-391": "not_applicable",
    "EV-405": "not_applicable",
    "EV-409": "not_applicable",
    "EV-410": "not_applicable",
    "EV-426": "not_applicable",
    "EV-439": "not_applicable",
    "EV-453": "not_applicable",
    "EV-458": "not_applicable",
    "EV-511": "not_applicable",
    "EV-3": "not_applicable",
    "EV-9": "not_applicable",
    "EV-10": "not_applicable",
}

ALL_DEVOPS_EVIDENCE_CODES: tuple[str, ...] = tuple(r["code"] for r in DEVOPS_EVIDENCE_SEED_ROWS)

EVIDENCE_MASTER_NAME_ORDER: tuple[str, ...] = tuple(r["name"] for r in DEVOPS_EVIDENCE_SEED_ROWS)

# Ensure every catalog code has a strategy (defaults to not_applicable).
for _row in DEVOPS_EVIDENCE_SEED_ROWS:
    _c = _row["code"]
    if _c not in EVIDENCE_CODE_STRATEGY:
        EVIDENCE_CODE_STRATEGY[_c] = "not_applicable"  # type: ignore[assignment]

NOT_APPLICABLE_MESSAGES: dict[str, str] = {
    "default": "This control is not represented in Bitbucket Cloud REST APIs; use the system that owns the configuration (cloud, IAM, backup, etc.).",
}
